plugins {
    id 'com.android.application'
}

android {
    namespace 'xyz.robotispsoft.mathborprint'
    compileSdk 35

    defaultConfig {
        applicationId 'xyz.robotispsoft.mathborprint'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.sunmi:printerlibrary:1.0.18'
}
